version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - echo $CODEBUILD_INITIATOR
      - cd mfe-accounts
      - npm install -y npm@latest
      - npm install -g @angular/cli
      - rm package-lock.json
    pre_build:
      commands:
        - npm install
  build:
    commands:
      - echo Build started...
      - ng build
artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: mfe-accounts/dist
