version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm i
      - npm i -g @angular/cli
  build:
    commands:
      - ng build
